### ISSUE TITLE
No accounts

### ISSUE THREAD

**Issue by mariwing** [toringer/home-assistant-sbanken#12]
Hi,

Thanks for your work 👍  

I added the application but only get an "Customer Information" Sensor and no accounts. Are there anywhere I need to grant access for the API on account level or something similar?

**Comment by sepodele** [comment]
Same here.

Logger: homeassistant.components.sensor
Source: custom_components/sbanken/sbanken_api.py:129
Integration: sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 17:50:53 (4 occurrences)
Last logged: 17:50:54

sbanken: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
    await task
  File "/config/custom_components/sbanken/sbanken_entities.py", line 111, in async_update
    standing_orders = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sbanken/sbanken_api.py", line 129, in get_standing_orders
    return response["items"]
KeyError: 'items'

**Comment by sepodele** [comment]
That fixed my issue. Thanks. Btw, I don't really like having the customer information in HA. Especially the "CustomerId"...

**Comment by mariwing** [comment]
Thank you, this fixed my issues as well so I will close this issue.
