### ISSUE TITLE
Error setting up entry Sbanken for sensor

### ISSUE THREAD

**Issue by robinkanters** [toringer/home-assistant-sbanken#13]
After setup according to the guide, no entities show up and the following log line is shown.

Integration version 2.1.1.

Version | core-2021.12.10
-- | --
Installation Type | Home Assistant Core
Development | false
Supervisor | false
Docker | false
User | sc-homeassistant
Virtual Environment | true
Python Version | 3.8.12
Operating System Family | Linux
Operating System Version | 4.4.180+
CPU Architecture | x86_64
Timezone | Europe/Oslo

```
Logger: homeassistant.config_entries
Source: custom_components/sbanken/services.py:41
Integration: Sbanken ([documentation](https://github.com/toringer/home-assistant-sbanken), [issues](https://github.com/toringer/home-assistant-sbanken/issues))
First occurred: 12:51:15 AM (1 occurrences)
Last logged: 12:51:15 AM

Error setting up entry Sbanken for sensor
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/sensor/__init__.py", line 204, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 147, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/setup.py", line 309, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/var/packages/python38/target/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/volume1/@appdata/homeassistant/config/custom_components/sbanken/sensor.py", line 8, in <module>
    from .services import async_setup_services
  File "/volume1/@appdata/homeassistant/config/custom_components/sbanken/services.py", line 41, in <module>
    hass: HomeAssistant, entities: list[SbankenAccountSensor]
TypeError: 'type' object is not subscriptable
```

**Comment by toringer** [comment]
@robinkanters, still an issue? Are the client id and the secret correct? From the stack trace, I'm guessing the services class is getting en empty/invalid list of sensors. Empty/invalid list of sensors would indicate problems getting data for your account.

**Comment by robinkanters** [comment]
Unfortunately, yes. I just tested it and it still doesn't show any
entities. I've checked the credentials again, and they're definitely
correct.
